# Generated by Django 4.2.27 on 2026-02-02 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_statusorder_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='description',
            new_name='article',
        ),
    ]
